/**
 * flux.h  —  C99 public header for the FLUX compression engine
 *
 * Link against:
 *   Windows : flux_core_v1.dll  +  flux_core_v1.dll.lib  (import library)
 *   Linux   : libflux_core_v1.so    (-lflux_core_v1)
 *
 * Compile flags example (GCC / Clang, Linux):
 *   gcc -std=c99 -I/path/to/include -L/path/to/lib -lflux_core_v1 example.c -o example
 *
 * Compile flags example (MSVC, Windows):
 *   cl /std:c17 /I include example.c /link /LIBPATH:lib flux_core_v1.dll.lib
 *
 * ABI source of truth: crates/flux-core/src/ffi.rs  (#[repr(C)])
 * Do NOT edit this file to change the ABI; update ffi.rs and regenerate.
 */

#pragma once
#ifndef FLUX_H
#define FLUX_H

#include <stddef.h>   /* size_t         */
#include <stdint.h>   /* uint8_t, etc.  */

/* -------------------------------------------------------------------------
 * Platform export / import macros
 * -------------------------------------------------------------------------
 * When building the shared library itself, define FLUX_BUILDING_LIB.
 * Consumers linking against the shared library need no special define.
 * ------------------------------------------------------------------------- */
#if defined(_WIN32) || defined(__CYGWIN__)
#  ifdef FLUX_BUILDING_LIB
#    define FLUX_API __declspec(dllexport)
#  else
#    define FLUX_API __declspec(dllimport)
#  endif
#elif defined(__GNUC__) && __GNUC__ >= 4
#  define FLUX_API __attribute__((visibility("default")))
#else
#  define FLUX_API
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* =========================================================================
 * Enumerations
 * =========================================================================
 * All enums are #[repr(C)] on the Rust side → they map to C int (4 bytes).
 * ========================================================================= */

/**
 * FluxCompressionLevel — trade-off selector between speed and ratio.
 *
 *   FLUX_LEVEL_TINY     (0) —  256 KB window. Embedded / constrained targets.
 *   FLUX_LEVEL_FAST     (1) —    4 MB window. LZ77 → rANS, fastest throughput.
 *   FLUX_LEVEL_BALANCED (2) —   32 MB window. PPM → rANS, good speed + ratio. DEFAULT.
 *   FLUX_LEVEL_MAXIMUM  (3) —  128 MB window. Adaptive per-block path selection.
 *   FLUX_LEVEL_EXTREME  (4) —  256 MB window. Maximum compression, slowest.
 */
typedef enum FluxCompressionLevel {
    FLUX_LEVEL_TINY     = 0,
    FLUX_LEVEL_FAST     = 1,
    FLUX_LEVEL_BALANCED = 2,
    FLUX_LEVEL_MAXIMUM  = 3,
    FLUX_LEVEL_EXTREME  = 4
} FluxCompressionLevel;

/**
 * FluxResult — status code returned by every FLUX API function.
 *
 *   FLUX_OK                (0) — success.
 *   FLUX_ERR_GENERIC       (1) — unclassified error (including caught panics).
 *   FLUX_ERR_INVALID_PARAM (2) — a parameter value was out of range or malformed.
 *   FLUX_ERR_NULL_POINTER  (3) — a required pointer was NULL.
 *   FLUX_ERR_IO            (4) — filesystem / read / write error.
 *   FLUX_ERR_CORRUPT_DATA  (5) — archive magic, checksum, or structure invalid.
 *   FLUX_ERR_WRONG_PASS    (6) — password incorrect or Argon2id validation failed.
 *   FLUX_ERR_BUFFER_SMALL  (7) — output buffer too small; *output_len set to required size.
 *
 * Test for success:  result == FLUX_OK
 * Test for failure:  result != FLUX_OK
 */
typedef enum FluxResult {
    FLUX_OK                = 0,
    FLUX_ERR_GENERIC       = 1,
    FLUX_ERR_INVALID_PARAM = 2,
    FLUX_ERR_NULL_POINTER  = 3,
    FLUX_ERR_IO            = 4,
    FLUX_ERR_CORRUPT_DATA  = 5,
    FLUX_ERR_WRONG_PASS    = 6,
    FLUX_ERR_BUFFER_SMALL  = 7
} FluxResult;

/* =========================================================================
 * Structs
 * ========================================================================= */

/**
 * FluxProgressEvent — snapshot delivered to a FluxProgressCallback.
 *
 * All pointer fields are valid ONLY for the duration of the callback call.
 * Do NOT store current_file past the callback's return.
 *
 * Layout on LP64 (64-bit Linux / Windows):
 *   offset  0 : bytes_processed   (uint64_t, 8 bytes)
 *   offset  8 : bytes_total       (uint64_t, 8 bytes)
 *   offset 16 : current_file      (pointer,  8 bytes)
 *   offset 24 : compression_ratio (float,    4 bytes)
 *   offset 28 : detected_stride   (uint32_t, 4 bytes)
 *   offset 32 : buffer_fill_level (float,    4 bytes)
 *   offset 36 : [4-byte end-alignment pad]
 *   sizeof    : 40 bytes
 */
typedef struct FluxProgressEvent {
    /** Raw input bytes processed so far. */
    uint64_t bytes_processed;
    /** Total raw input bytes for the operation. */
    uint64_t bytes_total;
    /** Null-terminated UTF-8 path of the current file. NULL if not applicable.
     *  Valid ONLY for the duration of the callback invocation. */
    const char *current_file;
    /** Compression ratio so far: compressed_size / original_size (e.g. 0.35). */
    float compression_ratio;
    /** Byte stride (1–16) detected by the autocorrelation analyser. */
    uint32_t detected_stride;
    /** Fraction of the internal circular buffer that is full (0.0–1.0). */
    float buffer_fill_level;
} FluxProgressEvent;

/**
 * FluxOptions — configuration for all compress / decompress operations.
 *
 * Fields are ordered to eliminate interior padding on 64-bit platforms
 * (pointer first, then 32-bit fields, then the enum).
 *
 * Layout on LP64:
 *   offset  0 : password     (pointer, 8 bytes)
 *   offset  8 : thread_count (uint32_t, 4 bytes)
 *   offset 12 : block_size   (uint32_t, 4 bytes)
 *   offset 16 : level        (FluxCompressionLevel / int, 4 bytes)
 *   offset 20 : [4-byte end-alignment pad — not a field]
 *   sizeof    : 24 bytes
 *
 * Always zero-initialise before setting fields:
 *
 *   FluxOptions opts;
 *   memset(&opts, 0, sizeof(opts));
 *   opts.level = FLUX_LEVEL_BALANCED;
 */
typedef struct FluxOptions {
    /** Optional UTF-8 password for Argon2id encryption.
     *  NULL disables encryption.
     *  Must remain valid for the entire duration of the API call. */
    const char *password;
    /** Worker thread count.  0 = auto-detect from available CPU cores. */
    uint32_t thread_count;
    /** Block size override in bytes (e.g. 1048576 = 1 MB).  0 = automatic. */
    uint32_t block_size;
    /** Compression level / algorithm selector. */
    FluxCompressionLevel level;
} FluxOptions;

/* =========================================================================
 * Callback type
 * ========================================================================= */

/**
 * FluxProgressCallback — optional progress notification function pointer.
 *
 * @param event      Snapshot of the current operation state.  Passed by value.
 *                   All pointer fields inside it are valid ONLY during this call.
 * @param user_data  Opaque pointer supplied by the caller; the library never
 *                   dereferences it.
 *
 * The callback is invoked on the same thread that called compress/decompress.
 * Must return quickly — do not block or perform heavy I/O inside it.
 *
 * Pass NULL wherever a callback pointer is accepted to disable progress
 * reporting entirely.
 */
typedef void (*FluxProgressCallback)(FluxProgressEvent event, void *user_data);

/* =========================================================================
 * API functions
 * ========================================================================= */

/**
 * flux_v1_get_version — query the engine version string.
 *
 * @return  Pointer to a static, null-terminated ASCII string (e.g. "0.1.0").
 *          The pointer is permanently valid; do NOT free it.
 *
 * Thread-safe: yes — may be called concurrently from any thread.
 *
 *   printf("FLUX engine %s\n", flux_v1_get_version());
 */
FLUX_API const char *flux_v1_get_version(void);

/**
 * flux_v1_compress — compress an in-memory buffer.
 *
 * The input is packed as a single blob file inside a FLUX archive.  The
 * resulting archive bytes are written to the caller-allocated output buffer.
 * Use flux_v1_decompress to recover the original bytes (byte-perfect).
 *
 * Buffer sizing recommendation:
 *   size_t cap = input_len + input_len / 8 + 4096;
 *   uint8_t *out = malloc(cap);
 *   size_t out_len = cap;
 *   FluxResult r = flux_v1_compress(src, src_len, out, &out_len, opts, NULL, NULL);
 *
 * If FLUX_ERR_BUFFER_SMALL is returned, *output_len has been set to the
 * exact required capacity; reallocate and retry.
 *
 * @param input       Source data (may be NULL only when input_len == 0).
 * @param input_len   Number of source bytes.
 * @param output      Destination buffer; must hold at least *output_len bytes.
 * @param output_len  In/out: capacity on entry, bytes-written on success.
 * @param options     Compression configuration (passed by value).
 * @param callback    Progress callback; NULL to disable.
 * @param user_data   Opaque cookie forwarded to every callback call.
 *
 * @return FLUX_OK on success, or a FLUX_ERR_* code on failure.
 *
 * Ownership: all memory is caller-owned.  options.password must remain valid
 * for the duration of this call.
 *
 * Thread-safety: safe to call concurrently on disjoint buffers.
 */
FLUX_API FluxResult flux_v1_compress(
    const uint8_t        *input,
    size_t                input_len,
    uint8_t              *output,
    size_t               *output_len,
    FluxOptions           options,
    FluxProgressCallback  callback,
    void                 *user_data
);

/**
 * flux_v1_decompress — decompress a FLUX archive produced by flux_v1_compress.
 *
 * The archive must contain a single blob file ("input.bin") as created by
 * flux_v1_compress.  Multi-file archives created by flux_v1_compress_directory
 * are not supported through this function.
 *
 * Call flux_v1_get_decompressed_size first to determine the exact buffer size.
 *
 * If FLUX_ERR_BUFFER_SMALL is returned, *output_len has been set to the
 * required size.
 *
 * @param input       Compressed archive bytes.
 * @param input_len   Number of compressed bytes.
 * @param output      Destination buffer for the decompressed data.
 * @param output_len  In/out: capacity on entry, bytes-written on success.
 * @param options     Must supply password if the archive is encrypted.
 *
 * @return FLUX_OK on success, FLUX_ERR_WRONG_PASS if the password was wrong,
 *         FLUX_ERR_CORRUPT_DATA if the archive is malformed,
 *         FLUX_ERR_BUFFER_SMALL if the output buffer was too small.
 *
 * Thread-safety: safe to call concurrently on disjoint buffers.
 */
FLUX_API FluxResult flux_v1_decompress(
    const uint8_t *input,
    size_t         input_len,
    uint8_t       *output,
    size_t        *output_len,
    FluxOptions    options
);

/**
 * flux_v1_compress_directory — compress a directory tree or file into an archive.
 *
 * If src_dir points to a directory, the entire tree is archived recursively.
 * If src_dir points to a regular file, that file alone is archived.
 * dest_archive is created (or overwritten) at the given path.
 *
 * @param src_dir       Null-terminated UTF-8 path to source directory or file.
 * @param dest_archive  Null-terminated UTF-8 path for the output archive.
 * @param options       Compression configuration.
 * @param callback      Progress callback; NULL to disable.
 * @param user_data     Opaque cookie forwarded to every callback call.
 *
 * @return FLUX_OK on success, FLUX_ERR_IO if a path is inaccessible.
 *
 * Thread-safety: accesses the file system — no concurrent writers on dest_archive.
 */
FLUX_API FluxResult flux_v1_compress_directory(
    const char           *src_dir,
    const char           *dest_archive,
    FluxOptions           options,
    FluxProgressCallback  callback,
    void                 *user_data
);

/**
 * flux_v1_get_decompressed_size — read the original size from an archive header.
 *
 * Reads only the archive header (does NOT decompress the data).  Returns the
 * total uncompressed byte count stored in the header so the caller can
 * pre-allocate an exact output buffer for flux_v1_decompress.
 *
 * For encrypted archives, options.password must be supplied — the header is
 * encrypted and cannot be read without the correct key.  For unencrypted
 * archives, pass a zero-initialised FluxOptions.
 *
 * @param input      Compressed archive bytes produced by flux_v1_compress.
 * @param input_len  Number of compressed bytes.
 * @param options    Must contain the password for encrypted archives.
 * @param out_size   On success, set to the total original (uncompressed) size.
 *
 * @return FLUX_OK on success, FLUX_ERR_WRONG_PASS for wrong password,
 *         FLUX_ERR_CORRUPT_DATA for malformed archives.
 */
FLUX_API FluxResult flux_v1_get_decompressed_size(
    const uint8_t *input,
    size_t         input_len,
    FluxOptions    options,
    size_t        *out_size
);

/**
 * flux_v1_free_result — release any resources associated with a FluxResult.
 *
 * Currently a no-op: all result codes are plain enum values with no heap
 * ownership.  Call it for forward-compatibility — future versions may attach
 * error messages or context objects to results.
 *
 * @param result  A FluxResult value returned by any FLUX API function.
 *
 * Safe to call with FLUX_OK or any error code.
 */
FLUX_API void flux_v1_free_result(FluxResult result);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* FLUX_H */
